export const POKEMON_LIST = [
  { id: 1, name: "Bulbasaur", type: ["Planta", "Veneno"], rarity: "Infrecuente" },
  { id: 2, name: "Ivysaur", type: ["Planta", "Veneno"], rarity: "Infrecuente" },
  { id: 3, name: "Venusaur", type: ["Planta", "Veneno"], rarity: "Raro" },
  { id: 4, name: "Charmander", type: ["Fuego"], rarity: "Infrecuente" },
  { id: 5, name: "Charmeleon", type: ["Fuego"], rarity: "Infrecuente" },
  { id: 6, name: "Charizard", type: ["Fuego", "Volador"], rarity: "Raro" },
  { id: 7, name: "Squirtle", type: ["Agua"], rarity: "Infrecuente" },
  { id: 8, name: "Wartortle", type: ["Agua"], rarity: "Infrecuente" },
  { id: 9, name: "Blastoise", type: ["Agua"], rarity: "Raro" },
  { id: 10, name: "Caterpie", type: ["Bicho"], rarity: "Común" },
  { id: 11, name: "Metapod", type: ["Bicho"], rarity: "Común" },
  { id: 12, name: "Butterfree", type: ["Bicho", "Volador"], rarity: "Infrecuente" },
  { id: 13, name: "Weedle", type: ["Bicho", "Veneno"], rarity: "Común" },
  { id: 14, name: "Kakuna", type: ["Bicho", "Veneno"], rarity: "Común" },
  { id: 15, name: "Beedrill", type: ["Bicho", "Veneno"], rarity: "Infrecuente" },
  { id: 16, name: "Pidgey", type: ["Normal", "Volador"], rarity: "Común" },
  { id: 17, name: "Pidgeotto", type: ["Normal", "Volador"], rarity: "Infrecuente" },
  { id: 18, name: "Pidgeot", type: ["Normal", "Volador"], rarity: "Raro" },
  { id: 19, name: "Rattata", type: ["Normal"], rarity: "Común" },
  { id: 20, name: "Raticate", type: ["Normal"], rarity: "Infrecuente" },
  { id: 21, name: "Spearow", type: ["Normal", "Volador"], rarity: "Común" },
  { id: 22, name: "Fearow", type: ["Normal", "Volador"], rarity: "Infrecuente" },
  { id: 23, name: "Ekans", type: ["Veneno"], rarity: "Común" },
  { id: 24, name: "Arbok", type: ["Veneno"], rarity: "Infrecuente" },
  { id: 25, name: "Pikachu", type: ["Eléctrico"], rarity: "Infrecuente" },
  { id: 26, name: "Raichu", type: ["Eléctrico"], rarity: "Raro" },
  { id: 27, name: "Sandshrew", type: ["Tierra"], rarity: "Común" },
  { id: 28, name: "Sandslash", type: ["Tierra"], rarity: "Infrecuente" },
  { id: 29, name: "Nidoran♀", type: ["Veneno"], rarity: "Común" },
  { id: 30, name: "Nidorina", type: ["Veneno"], rarity: "Infrecuente" },
  { id: 31, name: "Nidoqueen", type: ["Veneno", "Tierra"], rarity: "Raro" },
  { id: 32, name: "Nidoran♂", type: ["Veneno"], rarity: "Común" },
  { id: 33, name: "Nidorino", type: ["Veneno"], rarity: "Infrecuente" },
  { id: 34, name: "Nidoking", type: ["Veneno", "Tierra"], rarity: "Raro" },
  { id: 35, name: "Clefairy", type: ["Hada"], rarity: "Infrecuente" },
  { id: 36, name: "Clefable", type: ["Hada"], rarity: "Raro" },
  { id: 37, name: "Vulpix", type: ["Fuego"], rarity: "Infrecuente" },
  { id: 38, name: "Ninetales", type: ["Fuego"], rarity: "Raro" },
  { id: 39, name: "Jigglypuff", type: ["Normal", "Hada"], rarity: "Común" },
  { id: 40, name: "Wigglytuff", type: ["Normal", "Hada"], rarity: "Raro" },
  { id: 41, name: "Zubat", type: ["Veneno", "Volador"], rarity: "Común" },
  { id: 42, name: "Golbat", type: ["Veneno", "Volador"], rarity: "Infrecuente" },
  { id: 43, name: "Oddish", type: ["Planta", "Veneno"], rarity: "Común" },
  { id: 44, name: "Gloom", type: ["Planta", "Veneno"], rarity: "Infrecuente" },
  { id: 45, name: "Vileplume", type: ["Planta", "Veneno"], rarity: "Raro" },
  { id: 46, name: "Paras", type: ["Bicho", "Planta"], rarity: "Común" },
  { id: 47, name: "Parasect", type: ["Bicho", "Planta"], rarity: "Infrecuente" },
  { id: 48, name: "Venonat", type: ["Bicho", "Veneno"], rarity: "Común" },
  { id: 49, name: "Venomoth", type: ["Bicho", "Veneno"], rarity: "Infrecuente" },
  { id: 50, name: "Diglett", type: ["Tierra"], rarity: "Común" },
  { id: 51, name: "Dugtrio", type: ["Tierra"], rarity: "Infrecuente" },
  { id: 52, name: "Meowth", type: ["Normal"], rarity: "Común" },
  { id: 53, name: "Persian", type: ["Normal"], rarity: "Infrecuente" },
  { id: 54, name: "Psyduck", type: ["Agua"], rarity: "Común" },
  { id: 55, name: "Golduck", type: ["Agua"], rarity: "Infrecuente" },
  { id: 56, name: "Mankey", type: ["Lucha"], rarity: "Común" },
  { id: 57, name: "Primeape", type: ["Lucha"], rarity: "Infrecuente" },
  { id: 58, name: "Growlithe", type: ["Fuego"], rarity: "Infrecuente" },
  { id: 59, name: "Arcanine", type: ["Fuego"], rarity: "Raro" },
  { id: 60, name: "Poliwag", type: ["Agua"], rarity: "Común" },
  { id: 61, name: "Poliwhirl", type: ["Agua"], rarity: "Infrecuente" },
  { id: 62, name: "Poliwrath", type: ["Agua", "Lucha"], rarity: "Raro" },
  { id: 63, name: "Abra", type: ["Psíquico"], rarity: "Común" },
  { id: 64, name: "Kadabra", type: ["Psíquico"], rarity: "Infrecuente" },
  { id: 65, name: "Alakazam", type: ["Psíquico"], rarity: "Raro" },
  { id: 66, name: "Machop", type: ["Lucha"], rarity: "Común" },
  { id: 67, name: "Machoke", type: ["Lucha"], rarity: "Infrecuente" },
  { id: 68, name: "Machamp", type: ["Lucha"], rarity: "Raro" },
  { id: 69, name: "Bellsprout", type: ["Planta", "Veneno"], rarity: "Común" },
  { id: 70, name: "Weepinbell", type: ["Planta", "Veneno"], rarity: "Infrecuente" },
  { id: 71, name: "Victreebel", type: ["Planta", "Veneno"], rarity: "Raro" },
  { id: 72, name: "Tentacool", type: ["Agua", "Veneno"], rarity: "Común" },
  { id: 73, name: "Tentacruel", type: ["Agua", "Veneno"], rarity: "Infrecuente" },
  { id: 74, name: "Geodude", type: ["Roca", "Tierra"], rarity: "Común" },
  { id: 75, name: "Graveler", type: ["Roca", "Tierra"], rarity: "Infrecuente" },
  { id: 76, name: "Golem", type: ["Roca", "Tierra"], rarity: "Raro" },
  { id: 77, name: "Ponyta", type: ["Fuego"], rarity: "Común" },
  { id: 78, name: "Rapidash", type: ["Fuego"], rarity: "Infrecuente" },
  { id: 79, name: "Slowpoke", type: ["Agua", "Psíquico"], rarity: "Común" },
  { id: 80, name: "Slowbro", type: ["Agua", "Psíquico"], rarity: "Infrecuente" },
  { id: 81, name: "Magnemite", type: ["Eléctrico", "Acero"], rarity: "Común" },
  { id: 82, name: "Magneton", type: ["Eléctrico", "Acero"], rarity: "Infrecuente" },
  { id: 83, name: "Farfetch'd", type: ["Normal", "Volador"], rarity: "Raro" },
  { id: 84, name: "Doduo", type: ["Normal", "Volador"], rarity: "Común" },
  { id: 85, name: "Dodrio", type: ["Normal", "Volador"], rarity: "Infrecuente" },
  { id: 86, name: "Seel", type: ["Agua"], rarity: "Común" },
  { id: 87, name: "Dewgong", type: ["Agua", "Hielo"], rarity: "Infrecuente" },
  { id: 88, name: "Grimer", type: ["Veneno"], rarity: "Común" },
  { id: 89, name: "Muk", type: ["Veneno"], rarity: "Infrecuente" },
  { id: 90, name: "Shellder", type: ["Agua"], rarity: "Común" },
  { id: 91, name: "Cloyster", type: ["Agua", "Hielo"], rarity: "Infrecuente" },
  { id: 92, name: "Gastly", type: ["Fantasma", "Veneno"], rarity: "Común" },
  { id: 93, name: "Haunter", type: ["Fantasma", "Veneno"], rarity: "Infrecuente" },
  { id: 94, name: "Gengar", type: ["Fantasma", "Veneno"], rarity: "Raro" },
  { id: 95, name: "Onix", type: ["Roca", "Tierra"], rarity: "Infrecuente" },
  { id: 96, name: "Drowzee", type: ["Psíquico"], rarity: "Común" },
  { id: 97, name: "Hypno", type: ["Psíquico"], rarity: "Infrecuente" },
  { id: 98, name: "Krabby", type: ["Agua"], rarity: "Común" },
  { id: 99, name: "Kingler", type: ["Agua"], rarity: "Infrecuente" },
  { id: 100, name: "Voltorb", type: ["Eléctrico"], rarity: "Común" },
  { id: 101, name: "Electrode", type: ["Eléctrico"], rarity: "Infrecuente" },
  { id: 102, name: "Exeggcute", type: ["Planta", "Psíquico"], rarity: "Común" },
  { id: 103, name: "Exeggutor", type: ["Planta", "Psíquico"], rarity: "Raro" },
  { id: 104, name: "Cubone", type: ["Tierra"], rarity: "Común" },
  { id: 105, name: "Marowak", type: ["Tierra"], rarity: "Infrecuente" },
  { id: 106, name: "Hitmonlee", type: ["Lucha"], rarity: "Raro" },
  { id: 107, name: "Hitmonchan", type: ["Lucha"], rarity: "Raro" },
  { id: 108, name: "Lickitung", type: ["Normal"], rarity: "Raro" },
  { id: 109, name: "Koffing", type: ["Veneno"], rarity: "Común" },
  { id: 110, name: "Weezing", type: ["Veneno"], rarity: "Infrecuente" },
  { id: 111, name: "Rhyhorn", type: ["Tierra", "Roca"], rarity: "Común" },
  { id: 112, name: "Rhydon", type: ["Tierra", "Roca"], rarity: "Infrecuente" },
  { id: 113, name: "Chansey", type: ["Normal"], rarity: "Raro" },
  { id: 114, name: "Tangela", type: ["Planta"], rarity: "Infrecuente" },
  { id: 115, name: "Kangaskhan", type: ["Normal"], rarity: "Raro" },
  { id: 116, name: "Horsea", type: ["Agua"], rarity: "Común" },
  { id: 117, name: "Seadra", type: ["Agua"], rarity: "Infrecuente" },
  { id: 118, name: "Goldeen", type: ["Agua"], rarity: "Común" },
  { id: 119, name: "Seaking", type: ["Agua"], rarity: "Infrecuente" },
  { id: 120, name: "Staryu", type: ["Agua"], rarity: "Común" },
  { id: 121, name: "Starmie", type: ["Agua", "Psíquico"], rarity: "Infrecuente" },
  { id: 122, name: "Mr. Mime", type: ["Psíquico", "Hada"], rarity: "Raro" },
  { id: 123, name: "Scyther", type: ["Bicho", "Volador"], rarity: "Raro" },
  { id: 124, name: "Jynx", type: ["Hielo", "Psíquico"], rarity: "Raro" },
  { id: 125, name: "Electabuzz", type: ["Eléctrico"], rarity: "Raro" },
  { id: 126, name: "Magmar", type: ["Fuego"], rarity: "Raro" },
  { id: 127, name: "Pinsir", type: ["Bicho"], rarity: "Raro" },
  { id: 128, name: "Tauros", type: ["Normal"], rarity: "Raro" },
  { id: 129, name: "Magikarp", type: ["Agua"], rarity: "Común" },
  { id: 130, name: "Gyarados", type: ["Agua", "Volador"], rarity: "Raro" },
  { id: 131, name: "Lapras", type: ["Agua", "Hielo"], rarity: "Raro" },
  { id: 132, name: "Ditto", type: ["Normal"], rarity: "Infrecuente" },
  { id: 133, name: "Eevee", type: ["Normal"], rarity: "Infrecuente" },
  { id: 134, name: "Vaporeon", type: ["Agua"], rarity: "Raro" },
  { id: 135, name: "Jolteon", type: ["Eléctrico"], rarity: "Raro" },
  { id: 136, name: "Flareon", type: ["Fuego"], rarity: "Raro" },
  { id: 137, name: "Porygon", type: ["Normal"], rarity: "Raro" },
  { id: 138, name: "Omanyte", type: ["Roca", "Agua"], rarity: "Raro" },
  { id: 139, name: "Omastar", type: ["Roca", "Agua"], rarity: "Raro" },
  { id: 140, name: "Kabuto", type: ["Roca", "Agua"], rarity: "Raro" },
  { id: 141, name: "Kabutops", type: ["Roca", "Agua"], rarity: "Raro" },
  { id: 142, name: "Aerodactyl", type: ["Roca", "Volador"], rarity: "Raro" },
  { id: 143, name: "Snorlax", type: ["Normal"], rarity: "Raro" },
  { id: 144, name: "Articuno", type: ["Hielo", "Volador"], rarity: "Legendario" },
  { id: 145, name: "Zapdos", type: ["Eléctrico", "Volador"], rarity: "Legendario" },
  { id: 146, name: "Moltres", type: ["Fuego", "Volador"], rarity: "Legendario" },
  { id: 147, name: "Dratini", type: ["Dragón"], rarity: "Infrecuente" },
  { id: 148, name: "Dragonair", type: ["Dragón"], rarity: "Raro" },
  { id: 149, name: "Dragonite", type: ["Dragón", "Volador"], rarity: "Legendario" },
  { id: 150, name: "Mewtwo", type: ["Psíquico"], rarity: "Legendario" },
  { id: 151, name: "Mew", type: ["Psíquico"], rarity: "Legendario" }
];